<a href="https://colab.research.google.com/github/jemayne/LinearAlgebra58051/blob/main/Week%208/LinAlg_58051_Imbat_System_of_Linear_Equations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$
J = \left\{
    \begin{array}\\
        x+3y+z=3\\ 
        7x -2y -z=1 \\
        -4x + 9y +2z=-5
    \end{array}
\right. $$

$$
\begin{bmatrix}1&3&1\\7&-2&-1\\-4&9&2\end{bmatrix} \cdot \begin{bmatrix}x\\ y\\ z\end{bmatrix} = \begin{bmatrix}3\\1\\-5\end{bmatrix}
$$

In [2]:
import numpy as np

In [9]:
X = np.array([
              [1,3,1],
              [7,-2,-1],
              [-4,9,2]
])

Y = np.array([
              [3],
              [1],
              [-5]
])

In [10]:
print("X = \n", X)
print("\nY = \n", Y)

X = 
 [[ 1  3  1]
 [ 7 -2 -1]
 [-4  9  2]]

Y = 
 [[ 3]
 [ 1]
 [-5]]


In [11]:
X_inv = np.linalg.inv(X)
Xinv_Y = X_inv @ Y

print(Xinv_Y)

[[ 0.76666667]
 [-2.13333333]
 [ 8.63333333]]


In [12]:
x_y = np.linalg.solve(X, Y)

print(x_y)

[[ 0.76666667]
 [-2.13333333]
 [ 8.63333333]]


In [13]:
ans1 = X @ Xinv_Y
np.allclose(ans1, Y)

True