<a href="https://colab.research.google.com/github/jemayne/LinearAlgebra58051/blob/main/Week%207/LinAlg_58051_Imbat_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
matrix1 = np.array([
                    [2,1,3],
                    [5,4,6],
                    [8,7,9],
])

matrix2 = np.array([
                    [4,2,6],
                    [9,7,5],
                    [3,6,2],
])

matrix3 = np.array([
                    [9,6,8],
                    [1,5,2],
                    [5,7,4],
])

1. COMMUTATIVE PROPERTY

$
AB \neq BA$


In [ ]:
AB = matrix1 @ matrix2
BA = matrix2 @ matrix1

In [ ]:
print("AB = \n", AB)
print("BA = \n", BA)

AB = 
 [[ 26  29  23]
 [ 74  74  62]
 [122 119 101]]
BA = 
 [[ 66  54  78]
 [ 93  72 114]
 [ 52  41  63]]


In [ ]:
np.array_equiv(AB, BA)

False


2. DISTRIBUTIVE PROPERTY

$
A(B + C) = AB + AC$



In [ ]:
A_BC = matrix1 @ (matrix2+matrix3)
AB_AC = (matrix1 @ matrix2) + (matrix1 @ matrix3)

In [ ]:
print("A(B+C) = \n", A_BC)
print("AB + AC = \n", AB_AC)

A(B+C) = 
 [[ 60  67  53]
 [153 166 134]
 [246 265 215]]
AB + AC = 
 [[ 60  67  53]
 [153 166 134]
 [246 265 215]]


In [ ]:
np.array_equiv(A_BC, AB_AC)

True

3. ASSIOCIATIVE PROPERTY

$(AB)C = A(BC)$



In [ ]:
AB_C = (matrix1 @ matrix2) @ matrix3
A_BC = matrix1 @ (matrix2 @ matrix3)

In [ ]:
print("(AB)C = \n", AB_C)
print("A(BC) = \n", A_BC)

(AB)C = 
 [[ 378  462  358]
 [1050 1248  988]
 [1722 2034 1618]]
A(BC) = 
 [[ 378  462  358]
 [1050 1248  988]
 [1722 2034 1618]]


In [ ]:
np.array_equiv(AB_C, A_BC)

True

4. MULTIPLICATIVE IDENTITY PROPERTY

$AI = A $



In [ ]:
I = np.eye(3, dtype = int)
AI = matrix1 @ I

In [ ]:
print("AI = \n", AI)
print("A = \n", matrix1)

AI = 
 [[2 1 3]
 [5 4 6]
 [8 7 9]]
A = 
 [[2 1 3]
 [5 4 6]
 [8 7 9]]


In [ ]:
np.array_equiv(AI, matrix1)

True

5. MULTIPLICATIVE PROPERTY OF ZERO

$A0 = 0$

In [ ]:
zero = np.zeros(matrix1.shape)
A_zero = matrix1 @ zero

In [ ]:
print("A0 = \n", A_zero)
print("zero = \n", zero)

A0 = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
zero = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
np.array_equiv(zero, A_zero)

True

6. TRANSPOSITION PROPERTY OF MULTIPLICATION

$A\cdot A^{-1} = I$


In [ ]:
mat2 = matrix2 @ np.linalg.inv(matrix2)
I = np.eye(3,dtype=int)

In [ ]:
print("A(A inv) = \n", mat2.astype(int))
print("I = \n", I)

A(A inv) = 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
I = 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
np.array_equiv(mat2.astype(int), np.eye(3,dtype=int))

True