<a href="https://colab.research.google.com/github/jemayne/LinearAlgebra58051/blob/main/Week%206/LinAlg_58051_Imbat_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
matrix1 = np.array([
                    [3,2,4],
                    [6,2,7],
                    [1,4,2]
])

matrix2 = np.array([
                    [9,2,4],
                    [1,5,3],
                    [3,1,4]
])

matrix3 = np.array([
                    [1,6,5],
                    [3,4,7],
                    [2,3,7]
])

matrix4 = np.array([
                    [4,9,5],
                    [6,4,1],
                    [3,5,7]
])

matrix5 = np.array([
                    [1,2,3],
                    [6,2,4],
                    [8,7,9]
])


In [ ]:
matrix6 = np.array([
                    [0,0,0],
                    [0,0,0],
                    [0,0,0]
])

In [ ]:
def mat_desc(matrix):
  
  if matrix.size > 0:
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nSize:\t{matrix.size}\n')

    square = True if matrix.shape[0] == matrix.shape[1] else False
    print("The Matrix is square and not empty:", square)

    ones = np.all(matrix == 1)
    print("The matrix is ones:", ones)

    zeros = not np.any(matrix)
    print("The Matrix is zeros:", zeros)

    rows = len(matrix);
    colums = len(matrix[0]);
    identity: True
    for iteration in range(0, rows):
      for number in range(0, colums):
        if(iteration == number and matrix[iteration][number] !=1):
          identity = False
        if(iteration != number and matrix[iteration][number] !=0):
          identity = False

    if identity:
      print("The Matrix is an identity.")
    else:
      print("The Matrix is not an identity.")

  else:
    print("Does not apply")
    print("Does not apply")
    print("Does not apply")
    print("Does not apply")
    print("Matrix is empty")
    print("Does not apply")
    print("Does not apply")
    print("Does not apply")

In [ ]:
mat_desc(matrix1)

Matrix:
[[3 2 4]
 [6 2 7]
 [1 4 2]]

Shape:	(3, 3)
Rank:	2
Size:	9

The Matrix is square, and not empty: True
The matrix is ones: False
The Matrix is zeros: False
The Matrix is not an identity.


In [ ]:
mat_desc(matrix2)

Matrix:
[[9 2 4]
 [1 5 3]
 [3 1 4]]

Shape:	(3, 3)
Rank:	2
Size:	9

The Matrix is square, and not empty: True
The matrix is ones: False
The Matrix is zeros: False
The Matrix is not an identity.


In [ ]:
mat_desc(matrix3)

Matrix:
[[1 6 5]
 [3 4 7]
 [2 3 7]]

Shape:	(3, 3)
Rank:	2
Size:	9

The Matrix is square, and not empty: True
The matrix is ones: False
The Matrix is zeros: False
The Matrix is not an identity.


In [ ]:
mat_desc(matrix4)

Matrix:
[[4 9 5]
 [6 4 1]
 [3 5 7]]

Shape:	(3, 3)
Rank:	2
Size:	9

The Matrix is square, and not empty: True
The matrix is ones: False
The Matrix is zeros: False
The Matrix is not an identity.


In [ ]:
mat_desc(matrix5)

Matrix:
[[1 2 3]
 [6 2 4]
 [8 7 9]]

Shape:	(3, 3)
Rank:	2
Size:	9

The Matrix is square, and not empty: True
The matrix is ones: False
The Matrix is zeros: False
The Matrix is not an identity.


In [ ]:
mat_desc(matrix6)

Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Shape:	(3, 3)
Rank:	2
Size:	9

The Matrix is square, and not empty: True
The matrix is ones: False
The Matrix is zeros: True
The Matrix is not an identity.


In [ ]:
matrix1 = np.array([
                    [3,2,4],
                    [6,2,7],
                    [1,4,2]
])

matrix2 = np.array([
                    [9,2,4],
                    [1,5,3],
                    [3,1,4]
])

matrix3 = np.array([
                    [1,6,5],
                    [3,4,7],
                    [2,3,7]
])

matrix4 = np.array([
                    [4,9,5],
                    [6,4,1],
                    [3,5,7]
])

matrix5 = np.array([
                    [1,2,3],
                    [6,2,4],
                    [8,7,9]
])


In [ ]:
def mat_operations(A, B):
  print("First Matrix: \n", A)
  scalar1 = isinstance(A, (int, bytes, float, complex))
  print("The Matrix is scalar.", scalar1)

  print("Second Matrix: \n", B)
  scalar2 = isinstance(B, (int, bytes, float, complex))
  print("The Matrix is scalar.", scalar2)

  mat_1 = isinstance(A, np.ndarray)
  mat_2 = isinstance(B, np.ndarray)

  if scalar1 == True or scalar2 == True or mat_1 == True and mat_2 == True and A.shape == B.shape:
    print(f'\nMatA + MatB = \n{A+B}\n\nMatA - MatB=\n{A-B}\n\nMatA * MatB=\n{A*B}\n\nMatA / MatB =\t\n{A/B}')
  elif mat_2 == True and mat_2 == True and A.shape == B.shape:
    print("Cannot perform the operations")





In [ ]:
mat_operations(matrix1, matrix2)

First Matrix: 
 [[3 2 4]
 [6 2 7]
 [1 4 2]]
The Matrix is scalar. False
Second Matrix: 
 [[9 2 4]
 [1 5 3]
 [3 1 4]]
The Matrix is scalar. False

MatA + MatB = 
[[12  4  8]
 [ 7  7 10]
 [ 4  5  6]]

MatA - MatB=
[[-6  0  0]
 [ 5 -3  4]
 [-2  3 -2]]

MatA * MatB=
[[27  4 16]
 [ 6 10 21]
 [ 3  4  8]]

MatA / MatB =	
[[0.33333333 1.         1.        ]
 [6.         0.4        2.33333333]
 [0.33333333 4.         0.5       ]]
